# Site settings
title: Malta
client:
  name: Insel der Vielfalt
  link: http://bit.ly/2USfwzO
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Auf dem maltesischen Archipel treffen die Kulturen der Römer, Mauren, Johanniter, Franzosen und Briten auf sizilianische Küche und türkisfarbene Lagunen – und versprechen mediterranes Urlaubsglück für jeden Geschmack
# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/malta" # the subpath of your site, e.g. /blog/
img:     "/de/malta/_assets/img"
css:     "/de/malta/_assets/css"
js:      "/de/malta/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
